name: publish

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm install && npm test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - run: |
        npm config set //npm.pkg.github.com/:_authToken ${TOKEN}
        npm install
        npm publish
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
